//
// Created by rudra on 20-03-2026.
//

#ifndef AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_FAN_H
#define AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_FAN_H

#endif //AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_FAN_H