//
// Created by rudra on 15-02-2026.
//

#ifndef AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_CONFIG_H
#define AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_CONFIG_H

#define PIR_PIN 14
#define RELAY_PIN 27

const char* WIFI_SSID = "YOUR_WIFI";
const char* WIFI_PASS = "YOUR_PASSWORD";

#endif //AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_CONFIG_H

