//
// Created by rudra on 15-02-2026.
//

#ifndef AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_MOTION_H
#define AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_MOTION_H

void motionInit();
void motionCheck();

#endif //AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_MOTION_H
