//
// Created by rudra on 15-02-2026.
//

#ifndef AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_RELAY_H
#define AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_RELAY_H

void relayInit();
void relayOn();
void relayOff();

#endif //AI_BASED_VOICE_AND_MOTION_CONTROLLED_SMART_LIGHT_SYSTEM_RELAY_H
